spring:
  application:
    name: hack-vp-user
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/video_auth}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:change-me-super-secret-key}
    issuer: ${JWT_ISSUER:auth-service}

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

probe:
  path: /actuator/health
  port: http
  initialDelaySecondsLiveness: 120
  initialDelaySecondsReadness: 120
